name: vocalign
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - intel-openmp=2023.1.0
  - mkl=2023.1.0
  - tbb=2021.8.0
  - pip
  - pip:
    - openmim
    - -e ./mmengine_custom
    - -e .
variables:
  PYTHONPATH: .:./CAT-Seg # Assumes users run the code from the root directory
